#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/10-haraka-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-haraka ]; then



  echo 'Initialization Complete' >/tmp/state/10-haraka
fi

echo ''
echo '** Starting Haraka'
exec haraka -c /data/
