#!/usr/bin/with-contenv bash

DEBUG_MODE=${DEBUG_MODE:-"FALSE"}

if [[ "$DEBUG_MODE" = "TRUE" ]] && [[ "$DEBUG_MODE" = "true" ]]; then
	set -x
fi

### Set Defaults
	MANUAL_CONFIG=${MANUAL_CONFIG:-"FALSE"}
	ACCEPT_DOMAINS=${ACCEPT_DOMAINS:-"example.com"}
	CLAMD_HOST=${CLAMD_HOST:-"clamd"}
	CLAMD_PORT=${CLAMD_PORT:-"3310"}
	EARLY_TALKER_DELAY=${EARLY_TALKER_DELAY:-"1000"}
	ENABLE_VMAIL=${ENABLE_VMAIL:="FALSE"}
    ENABLE_LDAP=${ENABLE_LDAP:="FALSE"}
    ENABLE_LMTP=${ENABLE_LMTP:="FALSE"}
	GROUP=${GROUP:-"haraka"}
	HOSTNAME=${HOSTNAME:-"host.example.com"}
	IGNORE_BAD_PLUGINS=${IGNORE_BAD_PLUGINS:-"TRUE"}
	INACTIVITY_TIME=${INACTIVITY_TIME:-"300"}
	LISTEN_ADDRESS=${LISTEN_ADDRESS:-"0.0.0.0"}
	LDAP_TLS=${LDAP_TLS:-FALSE}
	LMTP_HOST=${LMTP_HOST:-"lmtp"}
	LMTP_PORT=${LMTP_PORT:-"24"}
	LOG_FILE=${LOG_FILE:-"/var/log/haraka/haraka.log"}
	LOG_LEVEL=${LOG_LEVEL:-"INFO"}
	LOG_TIMESTAMP=${LOG_TIMESTAMP:-"TRUE"}
	MAXIMUM_MESSAGE_SIZE=${MAXIMUM_MESSAGE_SIZE:-"26214400"}
    MAX_UNRECOGNIZED_COMMANDS=${MAX_UNRECOGNIZED_COMMANDS:-"10"}
	MAX_RECEIVED_COUNT=${MAX_RECEIVED_COUNT:-"100"}
	NODES=${NODES:-"0"}
	OUTBOUND_CONCURRENCY_MAX=${OUTBOUND_CONCURRENCY_MAX:-"100"}
	RABBITMQ_HOST=${RABBITMQ_HOST:-"rabbitmq"}
	RABBITMQ_POST=${RABBITMQ_PORT:-"5672"}
	REDIS_DB=${REDIS_DB:-"1"}
	REDIS_HOST=${REDIS_HOST:-"redis"}
	REDIS_PORT=${REDIS_PORT:-"6379"}
	RSPAMD_HOST=${RSPAMD_HOST:-"rspamd"}
	RSPAMD_PORT=${RSPAMD_PORT:-"11333"}
	SMTP_GREETING=${SMTP_GREETING:-"SMTP Service"}
	SMTP_PORT=${SMTP_PORT:-"25"}
	SPAMASSASSIN_HOST=${SPAMASSASSIN_HOST:-"spamassassin"}
	SPAMASSASSIN_PORT=${SPAMASSASSIN_PORT:-"783"}
	SPOOL_AFTER=${SPOOL_AFTER:-"-1"}
	SPOOL_DIR=${SPOOL_DIR:-"/var/spool/haraka"}
	STRICT_RFC1869=${STRICT_RFC1869:-"FALSE"}
	TLS_CERT=${TLS_CERT:-"tls_cert.pem"}
	TLS_KEY=${TLS_KEY:-"tls_key.pem"}
	USER=${USER:-"haraka"}
	UUID_DENY_NUMBER=${UUID_DENY_NUMBER:-"6"}
	VMAIL_DIR=${VMAIL_DIR:-"/vmail"}

    AUTH_BRIDGE=${AUTH_BRIDGE:-false}
    AUTH_FLAT_FILE=${AUTH_FLAT_FILE:-false}
    AUTH_LDAP=${AUTH_LDAP:-false}
    AUTH_PROXY=${AUTH_PROXY:-false}
    AUTH_VPOPMAILD=${AUTH_VPOPMAILD:-false}

	PLUGIN_ACCESS=${PLUGIN_ACCESS:-"TRUE"}
	PLUGIN_ASN=${PLUGIN_ASN:-"FALSE"}
	PLUGIN_ATTACHMENT=${PLUGIN_ATTACHMENT:-"FALSE"}
	PLUGIN_BOUNCE=${PLUGIN_BOUNCE:-"FALSE"}
	PLUGIN_CLAMD=${PLUGIN_CLAMD:-"FALSE"}
	PLUGIN_DATA_HEADERS=${PLUGIN_DATA_HEADERS:-"FALSE"}
	PLUGIN_DATA_URIBL=${PLUGIN_DATA_URIBL:-"FALSE"}
	PLUGIN_DKIM_SIGN=${PLUGIN_DKIM_SIGN:-"FALSE"}
	PLUGIN_DKIM_VERIFY=${PLUGIN_DKIM_VERIFY:-"FALSE"}
	PLUGIN_DNSBL=${PLUGIN_DNSBL:-"TRUE"}
	PLUGIN_DNSWL=${PLUGIN_DNSBL:-"TRUE"}
	PLUGIN_EARLY_TALKER=${PLUGIN_EARLY_TALKER:-"FALSE"}
	PLUGIN_FCRDNS=${PLUGIN_FCRDNS:-"FALSE"}
	PLUGIN_GEOIP=${PLUGIN_GEOIP:-"FALSE"}
	PLUGIN_GRAPH=${PLUGIN_GRAPH:-"FALSE"}
	PLUGIN_GREYLIST=${PLUGIN_GREYLIST:-"FALSE"}
	PLUGIN_HELO_CHECKS=${PLUGIN_HELO_CHECKS:-"TRUE"}
	PLUGIN_KARMA=${PLUGIN_KARMA:-"FALSE"}
	PLUGIN_KNOWN_SENDERS=${PLUGIN_KNOWN_SENDERS:-"FALSE"}
	PLUGIN_LIMIT=${PLUGIN_LIMIT:-"TRUE"}
	PLUGIN_MAIL_FROM_IS_RESOLVABLE=${PLUGIN_MAIL_FROM_IS_RESOLVABLE:-"TRUE"}
    PLUGIN_MAX_UNRECOGNIZED_COMMANDS=${PLUGIN_MAX_UNRECOGNIZED_COMMANDS:-:"TRUE"}
	PLUGIN_P0F=${PLUGIN_P0F:-"FALSE"}
	PLUGIN_PROCESS_TITLE=${PLUGIN_PROCESS_TITLE:-"TRUE"}
	PLUGIN_RCPT_TO_LDAP=${PLUGIN_RCPT_TO_LDAP:-"FALSE"}
	PLUGIN_RELAY=${PLUGIN_RELAY:-"FALSE"}
	PLUGIN_RSPAMD=${PLUGIN_RSPAMD:-"FALSE"}
	PLUGIN_SPAMASSASSIN=${PLUGIN_SPAMASSASSIN:-"FALSE"}
	PLUGIN_SPF=${PLUGIN_SPF:-"FALSE"}
	PLUGIN_TOOBUSY_MAXLAG=${PLUGIN_TOOBUSY_MAXLAG:-"70"}
	PLUGIN_TOOBUSY=${PLUGIN_TOOBUSY:-"FALSE"}
	PLUGIN_TLS=${PLUGIN_TLS:-"TRUE"}
	PLUGIN_WATCH=${PLUGIN_WATCH:-"FALSE"}

    QUEUE_DISCARD=${QUEUE_DISCARD:-"FALSE"}
    QUEUE_LMTP=${QUEUE_LMTP:-"FALSE"}
    QUEUE_QMAIL_QUEUE=${QUEUE_QMAIL_QUEUE:-"FALSE"}
    QUEUE_RABBITMQ=${QUEUE_RABBITMQ:-"FALSE"}
    QUEUE_SMTP_BRIDGE=${QUEUE_SMTP_BRIDGE:-"FALSE"}
    QUEUE_SMTP_FORWARD=${QUEUE_SMTP_FORWARD:-"FALSE"}
    QUEUE_SMTP_PROXY=${QUEUE_SMTP_PROXY:-"FALSE"}


### Check to see if Data Exists, if not, create new configuration
	if [ ! -f /data/package.json ] ; then
	   echo "** [haraka] New Installation Detected"
	   haraka -i /data/
	fi

	if [ "$MANUAL_CONFIG" = "TRUE" ] || [ "$MANUAL_CONFIG" = "TRUE" ];  then
		echo '** [haraka] Manual Configuration Requested, Not updating any configuration files'
	else
    ### Update Config 
	cat <<EOF > /data/config/plugins
# Plugin ordering often matters, run 'haraka -o -c /path/to/haraka/config'
# to see the order plugins (and their hooks) will run in.
# To see a list of all plugins, run 'haraka -l'
# To see the help docs for a particular plugin, run 'haraka -h plugin.name'

#process_title
#syslog

########### CONNECT
#toobusy
#relay
##access
# connect.p0f
# geoip
# asn
# fcrdns
dnswl
dnsbl
# HELO
#early_talker
helo.checks
#ldap
#tls

########### AUTH
#auth/flat_file
#auth/auth_proxy
#auth/auth_bridge
#auth/auth_vpopmail.d

########### MAIL FROM
#dkim_verify
mail_from.is_resolvable
#spf

########### RCPT TO
rcpt_to.in_host_list
#qmail-deliverable
#rcpt_to.access
#rcpt_to.maxcount
#rcpt_to.routes

########### DATA
#prevent_credential_leaks
#bounce
data.headers
#data.uribl
#attachment
#avg
#clamd
#spamassassin
#rspamd
#dkim_sign
#karma
#limit

########### QUEUE
#queue/discard
#queue/lmtp
#queue/qmail-queue
#queue/quarantine
#queue/rabbitmq
#queue/smtp_bridge
#queue/smtp_forward
#queue/smtp_proxy

# MailDir Extension
#maildir/maildir

# Error Checking
max_unrecognized_commands

# HTTP
#graph
#watch        
EOF

	### Set Haraka Options
	  ## Set Hostname
		echo $HOSTNAME > /data/config/me
	  ## Set Domains to Accept Mail 	
		rm -rf /data/config/host_list
		domains=$(echo $ACCEPT_DOMAINS | tr " " "\n")
			for domain in $domains
				do
				    echo $domain >> /data/config/host_list
				done
	  ## Set Log Level
		echo LOG$LOG_LEVEL > /data/config/loglevel
		sed -i -e "/level=/c\level=$LOG_LEVEL" /data/config/log.ini

	  ## Define how long the UUID should be in logging
		echo $UUID_DENY_NUMBER > /data/config/deny_includes_uuid
		if [ "$STRICT_RFC1869" = "TRUE" ] || [ "$STRICT_RFC1869" = "true" ];  then
			echo '1' > /data/config/strict_rfc1869
		else
			echo '0' > /data/config/strict_rfc1869
		fi
	  ## Set Timestamps in Logs
		rm -rf /data/config/log_timestamps
		if [ "$LOG_TIMESTAMP" = "TRUE" ] || [ "$LOG_TIMESTAMP" = "true" ]; then
		    echo '1' > /data/config/log_timestamps
		    sed -i -e "/timestamps=/c\timestamps=true" /data/config/log.ini
		else 
			echo '0' > /data/config/log_timestamps
			sed -i -e "/timestamps=/c\timestamps=false" /data/config/log.ini
		fi
	  ## Set Maximuim Message Size
		echo $MAXIMUM_MESSAGE_SIZE > /data/config/databytes
	  ## Set Early Talker Delay
	    echo $EARLY_TALKER_DELAY > /data/config/early_talker_delay
	  ## Set Max Received Count
	    echo $MAX_RECEIVED_COUNT > /data/config/max_received_count 
	  ## Set Max Unrecognized Commands
	    echo $MAX_UNRECOGNIZED_COMMANDS > /data/config/max_unrecognized_commands 
	  ## Set Max Concurrency for Outbound SMTP
	    echo $OUTBOUND_CONCURRENCY_MAX > /data/config/outbound.concurrency_max
	  ## Set Greeting
	    echo $SMTP_GREETING > /data/config/smtpgreeting
	  ## Check for Outbound Bounce Message
      if [ ! -f "/data/config/outbound.bounce_message" ]; then
      	cp -R /assets/haraka/config/outbound.bounce_message /data/config/outbound.bounce_message
      fi
	  ## Set SMTP Options
	  if [ "$IGNORE_BAD_PLUGINS" = "TRUE" ] || [ "$IGNORE_BAD_PLUGINS" = "true" ]; then
	  	LOG_TIMESTAMP=1
	  else
	  	LOG_TIMESTAMP=0
	  fi

    cat <<EOF > /data/config/smtp.ini
listen=[::0]:25,[::0]:587
inactivity_timeout=$INACTIVITY_TIMEOUT 
user=$USER
group=$GROUP
ignore_bad_plugins=0
nodes=$NODES
daemonize=false
daemon_log_file=$LOG_FILE
daemon_pid_file=/var/run/haraka.pid
spool_dir=$SPOOL_DIR
spool_after=$SPOOL_AFTER
force_shutdown_timeout=30
EOF

if [ -n "$PUBLIC_IP" ]; then
echo 'public_ip='$PUBLIC_IP >>/data/config/smtp.ini
fi


cat <<EOF > /data/config/redis.ini
[server]
host = $REDIS_HOST
port = $REDIS_PORT
db = $REDIS_DB
EOF

### External Routing Configuration
  if [ "$ENABLE_VMAIL" = "TRUE" ] || [ "$ENABLE_VMAIL" = "true" ];  then
    if [ -d "$VMAIL_DIR" ] ; then
	     echo '** [haraka] No VMAIL_DIR detected'
	     mkdir -p $VMAIL_DIR
	     chown -R $USER $VMAIL_DIR
	fi
    sed -i -e "s/queue\/*/#queue\//g" /data/config/plugins
 	sed -i -e "/maildir\/maildir/c\#maildir\/maildir" /data/config/plugins
	cp -R /assets/plugins/maildir.js /data/plugins/
	rm -rf /data/config/maildir.ini
	cp -R /assets/haraka/config/maildir.ini /data/config/maildir.ini
	sed -i -e "path=/data/%d/%n/Maildir/c\path=$VMAIL_DIR/%d/%n/Maildir" /data/config/maildir.ini
 else
 	sed -i -e "/maildir\/maildir/c\#maildir\/maildir" /data/config/plugins
  fi

### Auth Configuration
    ## Bridge
	if [ "$AUTH_BRIDGE" = "TRUE" ] || [ "$AUTH_BRIDGE" = "true" ];  then
  		sed -i -e "/auth\/bridge/c\/auth\/bridge" /data/config/plugins
		if [ ! -f /data/config/smtp_bridge.ini ] ; then
       		cp -R /assets/haraka/config/smtp_bridge.ini /data/config/smtp_bridge.ini
    	fi
    	QUEUE_BRIDGE=TRUE
  	else
	sed -i -e "/auth\/bridge/c\#auth\/bridge" /data/config/plugins
  	fi

    ## Flat File
	if [ "$AUTH_FLAT_FILE" = "TRUE" ] || [ "$AUTH_FLAT_FILE" = "true" ];  then
  		sed -i -e "/auth\/flat_file/c\auth\/flat_file" /data/config/plugins
		if [ ! -f /data/config/auth_flat_file.ini ] ; then
       		cp -R /assets/haraka/config/auth_flat_file.ini /data/config/auth_flat_file.ini
    	fi
  		else
		sed -i -e "/auth\/flat_file/c\#auth\/flat_file" /data/config/plugins
  	fi

	## LDAP (Also does auth, aliases, rcpt_to and authz)
	if [ "$AUTH_LDAP" = "TRUE" ] || [ "$AUTH_LDAP" = "true" ];  then

	    if [ "$LDAP_TLS" = "TRUE" ] || [ "$LDAP_TLS" = "true" ];  then
	        LDAP_SCHEME="ldaps://"
	    	if [ ! -n $LDAP_PORT ]; then
	    		LDAP_PORT=636
	    	fi
	    else
	    	LDAP_SCHEME="ldap://"
	    	if [ ! -n $LDAP_PORT ]; then
	    		LDAP_PORT=389
	    	fi
	    fi
		sed -i -e "/ldap/c\ldap" /data/config/plugins
		if [ ! -f /data/config/ldap.ini ] ; then
		   cp -R /assets/haraka/config/ldap.ini /data/config/ldap.ini
		fi
		    sed -i -e "/server\[\] = /c\server\[\] = $LDAP_SCHEME$LDAP_HOST:$LDAP_PORT" /data/config/ldap.ini
		    sed -i -e "/binddn = /c\binddn = $LDAP_BIND_DN" /data/config/ldap.ini
		    sed -i -e "/bindpw = /c\bindpw = $LDAP_BIND_PASS" /data/config/ldap.ini
		    sed -i -e "/basedn = /c\basedn = $LDAP_BASE_DN" /data/config/ldap.ini
	  	else
	  		sed -i -e "/ldap/c\#ldap" /data/config/plugins
	fi

    ## Proxy
	if [ "$AUTH_PROXY" = "TRUE" ] || [ "$AUTH_PROXY" = "true" ];  then
		sed -i -e "/auth\/proxy/c\auth\/proxy" /data/config/plugins
		if [ ! -f /data/config/auth_proxy.ini ] ; then
			cp -R /assets/haraka/config/auth_proxy.ini /data/config/auth_proxy.ini
		fi
		else
		sed -i -e "/auth\/proxy/c\#auth\/proxy" /data/config/plugins
	fi

    ## Vpopmail
	if [ "$AUTH_VPOPMAILD" = "TRUE" ] || [ "$AUTH_VPOPMAILD" = "true" ];  then
		sed -i -e "/auth\/vpopmail.d/c\auth\/vpopmail.d" /data/config/plugins
		if [ ! -f /data/config/auth_vpopmaild.ini ] ; then
		cp -R /assets/haraka/config/auth_vpopmaild.ini /data/config/auth_vpopmaild.ini
		fi
	else
		sed -i -e "/auth\/vpopmail.d/c\#auth\/vpopmail.d" /data/config/plugins
	fi

### Plugin Configuration
	 ## Access
	  if [ "$PLUGIN_ACCESS" = "TRUE" ] || [ "$PLUGIN_ACCESS" = "true" ];  then
		sed -i -e "/##access/c\access" /data/config/plugins
		if [ ! -f /data/config/access.ini ] ; then
		   cp -R /assets/haraka/config/access.* /data/config/
		fi
	  else
	  	sed -i -e "/access/c\##access" /data/config/plugins
	  fi
	 ## ASN
	  if [ "$PLUGIN_ASN" = "TRUE" ] || [ "$PLUGIN_ASN" = "true" ];  then
		sed -i -e "/asn/c\asn" /data/config/plugins
		if [ ! -f /data/config/asn.ini ] ; then
		   cp -R /assets/haraka/config/asn.ini /data/config/
		fi
		sed -i -e "/dbdir=/usr/local/share/GeoIP/c\dbdir=/usr/local/share/GeoIP" /data/config/asn.ini
		if [ ! -d /data/geoip ] ; then
		    mkdir -p /data/geoip
			echo '** [haraka] Downloading Initial GeoIP Database'
			maxmind-geolite-mirror
		fi
	  else
	  	sed -i -e "/asn/c\#asn" /data/config/plugins
	  fi
	 ## Attachment
	  if [ "$PLUGIN_ATTACHMENT" = "TRUE" ] || [ "$PLUGIN_ATTACHMENT" = "true" ];  then
		sed -i -e "/attachment/c\attachment" /data/config/plugins
		if [ ! -f /data/config/attachmment.ini ] ; then
		   cp -R /assets/haraka/config/attachment* /data/config/
		fi
	  else
	  	sed -i -e "/attachment/c\#attachment" /data/config/plugins
	  fi
	 ## Bounce
	  if [ "$PLUGIN_BOUNCE" = "TRUE" ] || [ "$PLUGIN_BOUNCE" = "true" ];  then
		sed -i -e "/bounce/c\bounce" /data/config/plugins
		if [ ! -f /data/config/bounce.ini ] ; then
		   cp -R /assets/haraka/config/bounce.ini /data/config/bounce.ini
		fi
	  else
	  	sed -i -e "/bounce/c\#bounce" /data/config/plugins
	  fi
	 ## Clam Antivirus
	  if [ "$PLUGIN_CLAMD" = "TRUE" ] || [ "$PLUGIN_CLAMD" = "true" ];  then
		sed -i -e "/clamd/c\clamd" /data/config/plugins
		if [ ! -f /data/config/clamd.ini ] ; then
		   cp -R /assets/haraka/config/clamd.ini /data/config/clamd.ini
		fi
	    sed -i -e "/clamd_socket=/c\spamd_socket=$CLAMD_HOST:$CLAMD_PORT" /data/config/clamd.ini
	  else
	  	sed -i -e "/clamd/c\#clamd" /data/config/plugins
	  fi
	 ## Data Headers
	  if [ "$PLUGIN_DATA_HEADERS" = "TRUE" ] || [ "$PLUGIN_DATA_HEADERS" = "true" ];  then
		sed -i -e "/data.headers/c\data.headers" /data/config/plugins
		if [ ! -f /data/config/data.headers.ini ] ; then
		   cp -R /assets/haraka/config/data.headers.ini /data/config/data.headers.ini
		fi
	  else
	  	sed -i -e "/data.headers/c\#data.headers" /data/config/plugins
	  fi
	 ## Data URI Blacklist
	  if [ "$PLUGIN_DATA_URIBL" = "TRUE" ] || [ "$PLUGIN_DATA_URIBL" = "true" ];  then
		sed -i -e "/data.uribl/c\data.uribl" /data/config/plugins
		if [ ! -f /data/config/data.uribl.ini ] ; then
		   cp -R /assets/haraka/config/data.uribl* /data/config/
		fi
	  else
	  	sed -i -e "/data.uribl/c\#data.uribl" /data/config/plugins
	  fi
	 ## DKIM Sign
	  if [ "$PLUGIN_DKIM_SIGN" = "TRUE" ] || [ "$PLUGIN_DKIM_SIGN" = "true" ];  then
		sed -i -e "/dkim_sign/c\dkim_sign" /data/config/plugins
		if [ ! -f /data/config/dkim_sign.ini ] ; then
		   cp -R /assets/haraka/config/dkim_sign.ini /data/config/dkim_sign.ini
		fi
		   chmod +x /data/config/dkim/dkim_key_gen.sh
		   cd /data/config/dkim/
		   dkim_domains=$(echo $DKIM_DOMAINS | tr " " "\n")
			for dkim_domain in $dkim_domains
				do
			        if [ ! -d "/data/config/dkim/$dkim_domain" ]; then
						./dkim_key_gen.sh $dkim_domain        
                    fi
				done
           sed -i -e "/disabled =/c\disabled = false" /data/config/dkim_sign.ini
	  else
	    sed -i -e "/dkim_sign/c\#dkim_sign" /data/config/plugins
	  fi
	 ## DKIM Verify
	  if [ "$PLUGIN_DKIM_VERIFY" = "TRUE" ] || [ "$PLUGIN_DKIM_VERIFY" = "true" ];  then
		sed -i -e "/dkim_verify/c\dkim_verify" /data/config/plugins
	  else
	    sed -i -e "/dkim_verify/c\#dkim_verify" /data/config/plugins
	  fi
	 ## DNS Blacklist Checks
	  if [ "$PLUGIN_DNSBL" = "TRUE" ] || [ "$PLUGIN_DNSBL" = "true" ];  then
		sed -i -e "/dnsbl/c\dnsbl" /data/config/plugins
		if [ ! -f /data/config/dnsbl.ini ] ; then
		   cp -R /assets/haraka/config/dnsbl* /data/config/
		fi
	  else
	  	sed -i -e "/dnsbl/c\#dnsbl" /data/config/plugins
	  fi
	 ## DNS Blacklist Checks
	  if [ "$PLUGIN_DNSWL" = "TRUE" ] || [ "$PLUGIN_DNSWL" = "true" ];  then
		sed -i -e "/dnswl/c\dnswl" /data/config/plugins
	  else
	  	sed -i -e "/dnswl/c\#dnswl" /data/config/plugins
	  fi

	 ## Early Talker
	  if [ "$PLUGIN_EARLY_TALKER" = "TRUE" ] || [ "$PLUGIN_EARLY_TALKER" = "true" ];  then
		sed -i -e "/early_talker/c\early_talker" /data/config/plugins
		if [ ! -f /data/config/early_talker.ini ] ; then
		   cp -R /assets/haraka/config/early_talker.ini /data/config/early_talker.ini
		fi
	  else
	  	sed -i -e "/early_talker/c\#early_talker" /data/config/plugins
	  fi
	 ## Forward Confirmed Reverse DNS
	  if [ "$PLUGIN_FCRDNS" = "TRUE" ] || [ "$PLUGIN_FCRDNS" = "true" ];  then
		sed -i -e "/fcrdns/c\fcrdns" /data/config/plugins
		if [ ! -f /data/config/connect.fcrdns.ini ] ; then
		   cp -R /assets/haraka/config/connect.fcrdns.ini /data/config/
		fi
	  else
	  	sed -i -e "/fcrdns/c\#fcrdns" /data/config/plugins
	  fi
	 ## GeoIP Lookup
	  if [ "$PLUGIN_GEOIP" = "TRUE" ] || [ "$PLUGIN_GEOIP" = "true" ];  then
		sed -i -e "/geoip/c\geoip" /data/config/plugins
		if [ ! -f /data/config/geoip.ini ] ; then
		   cp -R /assets/haraka/config/geoip.ini /data/config/geoip.ini
		fi
		sed -i -e "/dbdir=/c\dbdir=\/usr\/local\/share\/GeoIP" /data/config/geoip.ini
		if [ ! -d /data/geoip ] ; then
		    mkdir -p /data/geoip
			echo '** [haraka] Downloading Initial GeoIP Database'
			maxmind-geolite-mirror
		fi
	  else
	  	sed -i -e "/geoip/c\#geoip" /data/config/plugins
	  fi
	 ## Greylist
	  if [ "$PLUGIN_GREYLIST" = "TRUE" ] || [ "$PLUGIN_GREYLIST" = "true" ];  then
		sed -i -e "/greylist/c\greylist" /data/config/plugins
		if [ ! -f /data/config/greylist.ini ] ; then
		   cp -R /assets/haraka/config/greylist.ini /data/config/greylist.ini
		fi
	    sed -i -e "/db = /c\db = 11" /data/config/greylist.ini
	    sed -i -e "/host = /c\host = $REDIS_HOST" /data/config/greylist.ini
		sed -i -e "/port = /c\port = $REDIS_PORT" /data/config/greylist.ini
	  else
	  	sed -i -e "/greylist/c\#greylist" /data/config/plugins
	  fi
	 ## HELO Checks
	  if [ "$PLUGIN_HELO_CHECKS" = "TRUE" ] || [ "$PLUGIN_HELO_CHECKS" = "true" ];  then
		sed -i -e "/helo.checks/c\helo.checks" /data/config/plugins
		if [ ! -f /data/config/helo.checks.ini ] ; then
		   cp -R /assets/haraka/config/helo.checks.ini /data/config/helo.checks.ini
		fi
	  else
	  	sed -i -e "/helo.checks/c\#helo.checks" /data/config/plugins
	  fi
	 ## Karma
	  if [ "$PLUGIN_KARMA" = "TRUE" ] || [ "$PLUGIN_KARMA" = "true" ];  then
		sed -i -e "/karma/c\karma" /data/config/plugins
		if [ ! -f /data/config/karma.ini ] ; then
		   cp -R /assets/haraka/config/karma.ini /data/config/karma.ini
		fi
	    sed -i -e "/db     =/c\db   = 1" /data/config/karma.ini
	    sed -i -e "/host   =/c\host   = $REDIS_HOST" /data/config/karma.ini
		sed -i -e "/port   =/c\port   = $REDIS_PORT" /data/config/karma.ini
	  else
	  	sed -i -e "/karma/c\#karma" /data/config/plugins
	  fi
	 ## Known Senders
	  if [ "$PLUGIN_KNOWN_SENDERS" = "TRUE" ] || [ "$PLUGIN_KNOWN_SENDERS" = "true" ];  then
		sed -i -e "/known-senders/c\known-senders" /data/config/plugins
		if [ ! -f /data/config/known-senders.ini ] ; then
		   cp -R /assets/haraka/config/known-senders.ini /data/config/known-senders.ini
		fi
	    sed -i -e "/db     =/c\db     = 4" /data/config/known-senders.ini
	    sed -i -e "/host   =/c\host   = $REDIS_HOST" /data/config/known-senders.ini
		sed -i -e "/port   =/c\host   = $REDIS_PORT" /data/config/known-senders.ini
	  else
	  	sed -i -e "/known-senders/c\#known-senders" /data/config/plugins
	  fi
     
	 ## Limit
	  if [ "$PLUGIN_LIMIT" = "TRUE" ] || [ "$PLUGIN_LIMIT" = "true" ];  then
		sed -i -e "/limit/c\limit" /data/config/plugins
		if [ ! -f /data/config/limit.ini ] ; then
		   cp -R /assets/haraka/config/limit.ini /data/config/limit.ini
		fi
	    sed -i -e "/db=/c\db=4" /data/config/limit.ini
	    sed -i -e "/host=/c\host=$REDIS_HOST" /data/config/limit.ini
		sed -i -e "/port=/c\port=$REDIS_PORT" /data/config/limit.ini
	  else
	  	sed -i -e "/limit/c\#limit" /data/config/plugins
	  fi
	 ## Mail FROM is resolvable
	  if [ "$PLUGIN_MAIL_FROM_IS_RESOLVABLE" = "TRUE" ] || [ "$PLUGIN_MAIL_FROM_IS_RESOLVABLE" = "true" ];  then
		sed -i -e "/mail_from.is_resolvable/c\mail_from.is_resolvable" /data/config/plugins
		if [ ! -f /data/config/mail_from.is_resolvable.ini ] ; then
		   cp -R /assets/haraka/config/mail_from.is_resolvable.ini /data/config/mail_from.is_resolvable.ini
		fi
	  else
	  	sed -i -e "/mail_from.is_resolvable/c\#mail_from.is_resolvable" /data/config/plugins
	  fi
     ## Max Unrecognized Commands
	if [ "$PLUGIN_MAX_UNRECOGNIZED_COMMANDS" = "TRUE" ] || [ "$PLUGIN_MAX_UNRECOGNIZED_COMMANDS" = "true" ];  then
		sed -i -e "/max_unrecognized_commands/c\max_unrecognized_commands" /data/config/plugins
	  else
	  	sed -i -e "/max_unrecognized_commands/c\#max_unrecognized_commands" /data/config/plugins
	  fi
	 ## p0f
	  if [ "$PLUGIN_P0F" = "TRUE" ] || [ "$PLUGIN_P0F" = "true" ];  then
		sed -i -e "/connect.p0f/c\connect.p0f" /data/config/plugins
		if [ ! -f /data/config/connect.p0f.ini ] ; then
		   cp -R /assets/haraka/config/connect.p0f.ini /data/config/connect.p0f.ini
		fi
	  else
	  	sed -i -e "/connect.p0f/c\#connect.p0f" /data/config/plugins
	    s6-svc -d /var/run/s6/services/05-p0f
	  fi
	 ## Process Title
	  if [ "$PLUGIN_PROCESS_TITLE" = "TRUE" ] || [ "$PLUGIN_PROCESS_TITLE" = "true" ];  then
		sed -i -e "/process_title/c\process_title" /data/config/plugins
	  else
		sed -i -e "/process_title/c\#process_title" /data/config/plugins  	
	  fi
	 ## Recipient Exists in LDAP
	  if [ "$PLUGIN_RCPT_TO_LDAP" = "TRUE" ] || [ "$PLUGIN_RCPT_TO_LDAP" = "true" ];  then
		sed -i -e "/rcpt_to.ldap/c\rcpt_to.ldap" /data/config/plugins
		if [ ! -f /data/config/rcpt_to.ldap.ini ] ; then
		   cp -R /assets/haraka/config/rcpt_to.ldap.ini /data/config/
		fi
	    sed -i -e "/host = /c\host = $RSPAMD_HOST" /data/config/rspamd.ini
	    sed -i -e "/port = /c\port = $RSPAMD_PORT" /data/config/rspamd.ini
	  else
	  	sed -i -e "/rcpt_to.ldap/c\#rcpt_to.ldap" /data/config/plugins
	  fi
 	 ## Access
	  if [ "$PLUGIN_RELAY" = "TRUE" ] || [ "$PLUGIN_RELAY" = "true" ];  then
		sed -i -e "/relay/c\relay" /data/config/plugins
		if [ ! -f /data/config/relay.ini ] ; then
		   cp -R /assets/haraka/config/relay.ini /data/config/relay.ini
		fi
	  else
	  	sed -i -e "/relay/c\#relay" /data/config/plugins
	  fi

	 ## RSpamD
	  if [ "$PLUGIN_RSPAMD" = "TRUE" ] || [ "$PLUGIN_RSPAMD" = "true" ];  then
		sed -i -e "/rspamd/c\rspamd" /data/config/plugins
		if [ ! -f /data/config/rspamd.ini ] ; then
		   cp -R /assets/haraka/config/rspamd.ini /data/config/rspamd.ini
		fi
	    sed -i -e "/host = /c\host = $RSPAMD_HOST" /data/config/rspamd.ini
	    sed -i -e "/port = /c\port = $RSPAMD_PORT" /data/config/rspamd.ini
	  else
	  	sed -i -e "/rspamd/c\#rspamd" /data/config/plugins
	  fi
	 ## SPF
	  if [ "$PLUGIN_SPF" = "TRUE" ] || [ "$PLUGIN_SPF" = "true" ];  then
		sed -i -e "/spf/c\spf" /data/config/plugins
		if [ ! -f /data/config/spf.ini ] ; then
		   cp -R /assets/haraka/config/spf.ini /data/config/spf.ini
		fi
	  else
	  	sed -i -e "/spf/c\#spf" /data/config/plugins
	  fi
	 ## SpamAssassin
	  if [ "$PLUGIN_SPAMASSASSIN" = "TRUE" ] || [ "$PLUGIN_SPAMASSASSIN" = "true" ];  then
		sed -i -e "/spamassassin/c\spamassassin" /data/config/plugins
		if [ ! -f /data/config/spamassassin.ini ] ; then
		   cp -R /assets/haraka/config/spamassassin.ini /data/config/spamassasin.ini
		fi
	    sed -i -e "/spamd_socket=/c\spamd_socket=$SPAMASSASSIN_HOST:$SPAMASSASSIN_PORT" /data/config/spamassassin.ini
	  else
	  	sed -i -e "/spamassassin/c\#spamassassin" /data/config/plugins
	  fi
	 ## Too busy
	  if [ "$PLUGIN_TOOBUSY" = "TRUE" ] || [ "$PLUGIN_TOOBUSY" = "true" ];  then
		sed -i -e "/toobusy/c\toobusy" /data/config/plugins
		echo $PLUGIN_TOOBUSY_MAXLAG > /data/config/toobusy.maxlag 
	  else
	  	sed -i -e "/toobusy/c\#toobusy" /data/config/plugins
	  fi
	 ## TLS
	  if [ "$PLUGIN_TLS" = "TRUE" ] || [ "$PLUGIN_TLS" = "true" ];  then
		sed -i -e "/tls/c\tls" /data/config/plugins
		if [ ! -f /data/config/tls.ini ] ; then
		   cp -R /assets/haraka/config/tls.ini /data/config/tls.ini
		fi
        if [[ ! -f "/data/config/$TLS_CERT" ]] || [[ ! -f "/data/config/$TLS_KEY" ]]; then
		   echo '** [haraka] No TLS Certs Found, Autogenerating Self Signed Certificates'
		   	 	    cat <<EOF > /tmp/openssl.cnf
[ req ]
default_bits = 1024
encrypt_key = yes
distinguished_name = req_dn
x509_extensions = cert_type
prompt = no

[ req_dn ]
# country (2 letter code)
C=XX

# State or Province Name (full name)
ST=XX

# Locality Name (eg. city)
L=Earth

# Organization (eg. company)
O=Haraka

# Organizational Unit Name (eg. section)
OU=SMTP Server

# Common Name (*.example.com is also possible)
CN=$HOSTNAME

# E-mail contact
emailAddress=postmaster@${HOSTNAME#*.}

[ cert_type ]
nsCertType = server	 	
EOF

	 	openssl req -new -x509 -nodes -days 365 \
	                -config /tmp/openssl.cnf \
	                -out /data/config/$TLS_CERT \
	                -keyout /data/config/$TLS_KEY
	 	chmod -R 0600 /certs/*
	    rm -rf /tmp/openssl.cnf
		fi

        sed -i -e "/cert=/c\cert=$TLS_CERT" /data/config/tls.ini
        sed -i -e "/key=/c\key=$TLS_KEY" /data/config/tls.ini
	  else
	  	sed -i -e "/tls/c\#tls" /data/config/plugins
	  fi
	 ## Watch
	  if [ "$PLUGIN_WATCH" = "TRUE" ] || [ "$PLUGIN_WATCH" = "true" ];  then
		sed -i -e "/watch/c\watch" /data/config/plugins
		if [ ! -f /data/config/watch.ini ] ; then
		   cp -R /assets/haraka/config/watch.ini /data/config/watch.ini
		fi
		if [ ! -f /data/config/http.ini ] ; then
		   cp -R /assets/haraka/config/http.ini /data/config/http.ini
		fi
	  else
	  	sed -i -e "/watch/c\#watch" /data/config/plugins
	  fi


	## Setup Cron Task for GeoIP
	  if [ "$PLUGIN_GEOIP" = "TRUE" ] || [ "$PLUGIN_GEOIP" = "true" ] || [ "$PLUGIN_ASN" = "TRUE" ] || [ "$PLUGIN_ASN" = "true" ];  then
	    echo '0 0 1 * * maxmind-geolite-mirror >/dev/null 2>&1' >>/assets/cron/crontab.txt
	  fi

	## HTTP Webserver
	  if [ "$PLUGIN_WATCH" = "TRUE" ] || [ "$PLUGIN_WATCH" = "true" ] || [ "$PLUGIN_GRAPH" = "TRUE" ] || [ "$PLUGIN_GRAPH" = "true" ];  then
		if [ ! -d "/data/html" ]; then
      	cp -R /assets/haraka/html /data/
      	fi
      	cp -R /assets/haraka/config/http.ini /data/config/http.ini
      else
      	rm -rf /data/config/http.ini
      fi


	  fi
### Queue Configuration
	## Discard
	  if [ "$QUEUE_DISCARD" = "TRUE" ] || [ "$QUEUE_DISCARD" = "true" ];  then
		sed -i -e "/queue\/discard/c\queue\/discard" /data/config/plugins
	  else
		sed -i -e "/queue\/discard/c\#queue\/discard" /data/config/plugins
	  fi  
	## LMTP
	  if [ "$QUEUE_LMTP" = "TRUE" ] || [ "$QUEUE_LMTP" = "true" ];  then
		sed -i -e "/queue\/lmtp/c\queue\/lmtp" /data/config/plugins
		if [ ! -f /data/config/lmtp.ini ] ; then
	       cp -R /assets/haraka/config/lmtp.ini /data/config/lmtp.ini
	    fi
	    sed -i -e "/host=/c\host=$LMTP_HOST" /data/config/lmtp.ini
	    sed -i -e "/port=/c\port=$LMTP_PORT" /data/config/lmtp.ini
	  else
		sed -i -e "/queue\/lmtp/c\#queue\/lmtp" /data/config/plugins
	  fi  
	## Qmail
	  if [ "$QUEUE_QMAIL" = "TRUE" ] || [ "$QUEUE_QMAIL" = "true" ];  then
		sed -i -e "/queue\/qmail-queue/c\queue\/qmail-queue" /data/config/plugins
		if [ ! -f /data/config/qmail-queue.ini ] ; then
	       cp -R /assets/haraka/config/qmail-queue.ini /data/config/qmail-queue.ini
	    fi
	  else
		sed -i -e "/queue\/qmail-queue/c\#queue\/qmail-queue" /data/config/plugins
	  fi  
	## Quarantine
	  if [ "$QUEUE_QUARANTINE" = "TRUE" ] || [ "$QUEUE_QUARANTINE" = "true" ];  then
		sed -i -e "/queue\/quarantine/c\queue\/quarantine" /data/config/plugins
		if [ ! -f /data/config/quarantine.ini ] ; then
	       cp -R /assets/haraka/config/quarantine.ini /data/config/quarantine.ini
	    fi
	  else
		sed -i -e "/queue\/quarantine/c\#queue\/quarantine" /data/config/plugins
	  fi  
	## Quarantine
	  if [ "$QUEUE_RABBITMQ" = "TRUE" ] || [ "$QUEUE_RABBITMQ" = "true" ];  then
		sed -i -e "/queue\/rabbitmq/c\queue\/rabbitmq" /data/config/plugins
		if [ ! -f /data/config/rabbitmq.ini ] ; then
	       cp -R /assets/haraka/config/rabbitmq.ini /data/config/rabbitmq.ini
	    fi
	    sed -i -e "/server_ip = /c\server_ip = $RABBITMQ_HOST" /data/config/rabbitmq.ini
	    sed -i -e "/server_port = /c\server_port = $RABBITMQ_PORT" /data/config/rabbitmq.ini
	  else
		sed -i -e "/queue\/rabbitmq/c\#queue\/rabbitmq" /data/config/plugins
	  fi  
	## SMTP Bridge
	  if [ "$QUEUE_SMTP_BRIDGE" = "TRUE" ] || [ "$QUEUE_SMTP_BRIDGE" = "true" ];  then
		sed -i -e "/queue\/smtp_bridge/c\queue\/smtp_bridge" /data/config/plugins
		if [ ! -f /data/config/smtp_bridge.ini ] ; then
	       cp -R /assets/haraka/config/smtp_bridge.ini /data/config/smtp_bridge.ini
	    fi
	    AUTH_BRIDGE=TRUE
	  else
		sed -i -e "/queue\/smtp_bridge/c\#queue\/smtp_bridge" /data/config/plugins
	  fi  
	## SMTP Forward
	  if [ "$QUEUE_SMTP_FORWARD" = "TRUE" ] || [ "$QUEUE_SMTP_FORWARD" = "true" ];  then
		sed -i -e "/queue\/smtp_forward/c\queue\/smtp_forward" /data/config/plugins
		if [ ! -f /data/config/smtp_forward.ini ] ; then
	       cp -R /assets/haraka/config/smtp_forward.ini /data/config/smtp_forward.ini
	    fi
	  else
		sed -i -e "/queue\/smtp_forward/c\#queue\/smtp_forward" /data/config/plugins
	  fi  
	## SMTP Proxy
	  if [ "$QUEUE_SMTP_PROXY" = "TRUE" ] || [ "$QUEUE_SMTP_PROXY" = "true" ];  then
		sed -i -e "/queue\/smtp_proxy/c\queue\/smtp_proxy" /data/config/plugins
		if [ ! -f /data/config/smtp_proxy.ini ] ; then
	       cp -R /assets/haraka/config/smtp_proxy.ini /data/config/smtp_proxy.ini
	    fi
	  else
		sed -i -e "/queue\/smtp_proxy/c\#queue\/smtp_proxy" /data/config/plugins
	  fi  

### Output what plugins are enabled
AUTH_ENABLED=`set -o posix; set | sort | grep AUTH | grep TRUE |sed -e 's/AUTH_//g' | sed -e 's/=TRUE//g' | awk -vRS="" -vOFS=', ' '$1=$1' | tr A-Z a-z`
echo '** [haraka] Enabling the following authentication methods: '$AUTH_ENABLED

PLUGINS_ENABLED=`set -o posix; set | sort | grep PLUGIN | grep TRUE |sed -e 's/PLUGIN_//g' | sed -e 's/=TRUE//g' | awk -vRS="" -vOFS=', ' '$1=$1' | tr A-Z a-z`
echo '** [haraka] Enabling the following plugins: '$PLUGINS_ENABLED

QUEUES_ENABLED=`set -o posix; set | sort | grep QUEUE | grep TRUE |sed -e 's/QUEUE_//g' | sed -e 's/=TRUE//g' | awk -vRS="" -vOFS=', ' '$1=$1' | tr A-Z a-z`
echo '** [haraka] Enabling the following queues: '$QUEUES_ENABLED

fi


mkdir -p `dirname $LOG_FILE`
touch $LOG_FILE
chown -R $USER:$GROUP `dirname $LOG_FILE`
mkdir -p $SPOOL_DIR
chown -R $USER:$GROUP /data $SPOOL_DIR
mkdir -p /tmp/state
touch /tmp/state/10-haraka-init